name: syncfusion_localizations
description: Syncfusion Localizations package contains localized text for 77 cultures for all the applicable Syncfusion Flutter Widgets. 
version: 24.1.41
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_localizations

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  syncfusion_flutter_core:
      path: ../syncfusion_flutter_core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
