name: syncfusion_flutter_gauges
description: The Flutter gauges library includes a linear gauge and radial gauge (a.k.a. circular gauge) to create modern, interactive, animated gauges and radial sliders.
version: 24.1.41
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_gauges

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core:
      path: ../syncfusion_flutter_core
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 
