name: syncfusion_flutter_sliders
description: A Flutter Sliders library for creating highly customizable and UI-rich slider, range slider, and range selector widgets for filtering purposes.
version: 23.2.5 
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_sliders

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0

  syncfusion_flutter_core:
      path: ../syncfusion_flutter_core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
